version: '3.4'

services:
  gab_core:
    # image: ${DOCKER_REGISTRY-}gabcore
    build:
      context: ..
      dockerfile: GaB_Core/dev.Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"

  postgresql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  default:
  
volumes:
  db-data:
    external: true
