name: Docker

on:
  push:
    branches: [ "master" ]
    paths: ["GaB_Core/GaB_Core.csproj"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Get version
        shell: bash
        run: |
          read_dom () { local IFS=\> ; read -d \< ENTITY CONTENT ;}
          while read_dom; do
              if [[ $ENTITY = "AssemblyVersion" ]]; then
              echo "VERSION=$CONTENT" >> $GITHUB_ENV
              echo "VERSION=$CONTENT"
              exit
              fi
          done < GaB_Core/GaB_Core.csproj
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: push with version tag 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: GaB_Core/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORY_USERNAME }}/core:${{env.VERSION}}
      -
        name: push with latest tag 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: GaB_Core/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORY_USERNAME }}/core:latest
