name: version-change-check

on:
  pull_request:
    branches:    
      - master

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Get PR number
        run: |
          echo "PR_NUMBER=${{ github.ref_name }}" | sed -E 's!/merge!' >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.ref_name }}" | sed -E 's!/merge!'
      - 
        name: Get files
        run: gh pr view ${{ env.PR_NUMBER }} --json files --jq '.files.[].path'
        env:
          GH_TOKEN: ${{ secrets.CLI_TOKEN }}
