name: version-change-check

on:
  pull_request:
    branches:    
      - master

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Get files
        run: gh pr view ${{ github.ref }} --json files --jq '.files.[].path'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
