name: version-change-check

on:
  pull_request:
    branches:    
      - master

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Get PR number
        run: |
          echo "PR_NUMBER=${{ github.ref_name }}" | sed 's!/merge!!' - >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.ref_name }}" | sed 's!/merge!!' -
      - 
        name: Get files
        run: |
          gh alias set pr_files "pr view $1 --json files --jq '.files.[].path'"
          gh pr_files ${{ env.PR_NUMBER }} | cat
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
